/* Project data + utilities */
const PROJECTS = [
  {
    id: "automotive-hmi",
    title: "Automotive Digital Experience",
    client: "Confidential global automotive company",
    team: "Cross-functional design + concept engineering",
    role: "Senior Product Designer · Sub-Lead UX/UI",
    industry: "Automotive",
    brand: "#0A0A0A",
    summary: "In-car digital experiences for a global automotive company — UX flows, system settings, and embedded interface patterns.",
    lede: "I worked with a global automotive company on confidential in-car digital experiences, contributing to product areas where usability, safety, technical feasibility, and brand consistency were equally critical.",
    nda: "Due to NDA restrictions, product screens and detailed flows cannot be publicly shown. This case study focuses on my role, design approach, stakeholder collaboration, and the type of product challenges addressed.",
    transitionReason: "The project scope was reduced due to budget constraints.",
    sectionsTitle: "Role & responsibilities",
    sectionsIntro: "As a Senior Product Designer and Sub-Lead, I supported the design of in-car digital product experiences, working across discovery, UX definition, UI execution, and cross-functional alignment.",
    responsibilities: [
      "Leading UX/UI work for in-car digital products, balancing user needs, safety considerations, technical constraints, and platform consistency.",
      "Driving discovery initiatives, including user research, stakeholder interviews, problem framing, and opportunity definition.",
      "Translating complex product requirements into clear user flows, interaction models, and interface solutions.",
      "Collaborating closely with product managers, engineers, concept engineers, and stakeholders to align product vision with delivery feasibility.",
      "Ensuring design consistency across flows, components, and system-level patterns.",
      "Acting as a bridge between design, product, and engineering to unblock decisions and clarify requirements.",
    ],
    productAreas: [
      "In-car UX flows",
      "System settings and vehicle-related digital experiences",
      "Interaction patterns for embedded interfaces",
      "Design system alignment",
      "UX discovery and roadmap support",
      "Stakeholder and engineering collaboration",
      "Design documentation and handover",
    ],
    seniorHighlight: "Designing for in-car experiences means designing for moments where attention, safety, and time pressure shape every decision — and where every detail must align with the brand and platform it lives within.",
    tools: ["Figma", "FigJam", "Jira", "Confluence", "Adobe Creative Suite", "AI-supported internal tools"],
    tags: ["Automotive", "HMI", "Sub-Lead", "Confidential"],
  },
  {
    id: "bankinter",
    title: "Bankinter Digital Banking",
    client: "Bankinter",
    team: "3 designers (I led)",
    role: "Team Lead UX/UI",
    industry: "Banking",
    brand: "#FF6B00",
    summary: "Leading UX/UI for Bankinter's mobile and web banking — onboarding, KYC, transfers, account management, Open Banking.",
    lede: "I led UX/UI design for Bankinter's digital banking products, supporting the evolution of mobile and web banking experiences across key customer journeys — complex financial flows, regulatory considerations, technical constraints, and close collaboration with product and engineering teams.",
    nda: "Due to NDA restrictions, detailed product screens cannot be publicly displayed. The case study focuses on my leadership role, design scope, and the product areas where I contributed.",
    sectionsTitle: "Role & responsibilities",
    sectionsIntro: "As Team Lead UX/UI, I led a team of designers and worked closely with product managers, engineers, business stakeholders, and compliance-related teams to improve customer-facing banking experiences.",
    responsibilities: [
      "Leading UX/UI design across core banking flows, from analysis and problem framing to design delivery.",
      "Managing and mentoring a small design team — supporting quality, prioritisation, and consistency across deliverables.",
      "Collaborating with product managers and engineers to define feasible, user-centred solutions.",
      "Analysing existing functionality and identifying opportunities to improve usability, clarity, and conversion.",
      "Designing and refining flows based on UX research, business goals, technical constraints, and market-specific requirements.",
      "Supporting the creation of new flows and the optimisation of existing banking journeys.",
      "Helping establish design processes that improved collaboration, delivery quality, and team alignment.",
      "Ensuring interface consistency across product areas and alignment with design system principles.",
    ],
    productAreas: [
      "Onboarding",
      "KYC / Know Your Customer",
      "Account opening",
      "National transfers",
      "MB Way integration",
      "Account management",
      "Home credit",
      "Open Banking",
      "Omnichannel banking experiences",
    ],
    seniorHighlight: "This project demonstrates my ability to lead design in a regulated financial environment, where user experience must balance simplicity, trust, legal requirements, technical feasibility, and business objectives.",
    tools: ["Figma", "Sketch", "Adobe Creative Suite", "Jira", "Confluence", "Miro / FigJam"],
    tags: ["Banking", "Team Lead", "Regulated", "Design Systems"],
  },
  {
    /* Rich case-study — lives on the Work page only (excluded from featured) */
    id: "bankinter-bkwallet",
    title: "Bankinter — BKwallet",
    client: "Bankinter",
    team: "PM · several developers · 3 UX designers (I led)",
    role: "Team Lead UX/UI · UX Strategy",
    industry: "Banking · Fintech",
    brand: "#FF6B00",
    image: __r("assets/bk-hero.jpg"),
    summary: "Leading UX/UI for Bankinter's mobile wallet — payments, transfers, withdrawals, and digital card management inside the bank app.",
    lede: "I led the UX/UI design and discovery for BKwallet — a new function inside the Bankinter mobile app that brought together phone payments, MB Way, P2P transfers, and digital card management into a single coherent flow.",
    nda: "Some real product screens are shown here. The full flows, internal documentation, and customer data remain confidential under NDA — only what was approved for portfolio use appears below.",
    caseStudy: true,
    sections: [
      {
        kind: "goal",
        title: "Goal",
        body: "Enable payment with the phone inside the bank app — a brand-new function in the Bankinter product suite, replacing the need for a physical card or a separate wallet app.",
      },
      {
        kind: "process",
        title: "Process",
        steps: [
          { title: "Competitor analysis", notes: ["Validate international alternative ways of payment / transfers."] },
          { title: "Analysis of the requirements", notes: ["Validate it with the client.", "Validate with the Dev team."] },
          { title: "Logic App Map", notes: [] },
          { title: "Creating the user flow", notes: [] },
          { title: "Create wireframes", notes: ["Validate it with the client.", "Validate with the Dev team."] },
          { title: "Create prototype", notes: ["Test with users."] },
          { title: "Create a Beta version", notes: ["Receive feedback from the client (Call center)."] },
          { title: "Launch update", notes: ["Celebrate."] },
        ],
      },
      {
        kind: "image",
        title: "Analysis of the requirements",
        image: __r("assets/bk-analysis.jpg"),
        caption: "Mapping the SDK and host-to-host architecture between the bank and SIBS, identifying which interfaces and callbacks the new wallet flows would need.",
      },
      {
        kind: "image",
        title: "Logic Map",
        image: __r("assets/bk-logic.jpg"),
        caption: "The full BKwallet information architecture — eight top-level branches (Menu, Send & Receive, MBway Pay, Withdraw, Movements, Settings, Generate Cards, Card List) drilled down to every confirm/cancel terminal state.",
      },
      {
        kind: "image",
        title: "Creating the user flow",
        image: __r("assets/bk-userflow.jpg"),
        caption: "Eight stitched flows — Activate Wallet, Send Money, Split Bill, Pay with Wallet, Withdraw, Movements, Settings — each validated end-to-end with PM and engineering before moving into hi-fi.",
      },
      {
        kind: "image",
        title: "Send money — final UI",
        image: __r("assets/bk-ui-send.jpg"),
        caption: "The send-money flow: card selection, action picker (send / request / split), contact list with MB Way badges, and a confirmation card with cost transparency.",
      },
      {
        kind: "image",
        title: "Movements — final UI",
        image: __r("assets/bk-ui-movimentos.jpg"),
        caption: "A unified transaction view: pending and completed in one list, expandable per-recipient detail, and a one-tap reminder action for outstanding requests.",
      },
      {
        kind: "image",
        title: "Withdraw & Settings — final UI",
        image: __r("assets/bk-ui-settings.jpg"),
        caption: "Cardless ATM withdrawal with a time-bound code, plus the settings panel that lets users toggle NFC, daily limits, and per-card defaults — keeping security visible without making it heavy.",
      },
    ],
    myRoleTitle: "My role",
    myRoleIntro: "I led the design team and the design strategy for BKwallet end-to-end — discovery, design direction, validation, security review, and post-launch tracking.",
    myRole: [
      { title: "Strategic Leadership", body: "Defined the UX discovery strategy and the overall design approach for BKwallet — framing the problem, prioritising flows, and shaping the design direction with PM and engineering leadership." },
      { title: "Team Management", body: "Led and coached a team of UX designers throughout the project lifecycle — running design critiques, unblocking decisions, and growing their craft." },
      { title: "Design Validation", body: "Ensured every design was feasible — validating with developers, supporting them during implementation, and reviewing every released screen against the design intent." },
      { title: "Security & Compliance", body: "Worked with compliance and security teams to verify that every flow met strict banking, KYC, and regulatory requirements without compromising usability." },
      { title: "Performance Tracking", body: "Defined and monitored the success metrics post-launch — adoption, completion, support load — and fed the learnings back into the next release cycle." },
    ],
    /* Fictional metrics — for portfolio illustration */
    results: [
      { value: "+34%", label: "Payment completion rate", note: "vs. previous card-only flow (90-day post-launch)." },
      { value: "3.2 → 4.6", label: "App store rating", note: "iOS + Android combined, after the wallet release." },
      { value: "−28%", label: "Wallet-related support tickets", note: "compared to the pre-launch six-month baseline." },
      { value: "18s", label: "Median time to send money", note: "down from 45s on the previous transfer flow." },
      { value: "120k+", label: "Active wallet users in 6 months", note: "post-launch adoption across the customer base." },
      { value: "+52%", label: "Mobile app engagement", note: "weekly active sessions across the bank app." },
    ],
    tools: ["Figma", "Sketch", "Adobe XD", "Jira", "Confluence", "Miro / FigJam"],
    tags: ["Banking", "Team Lead", "Payments", "Mobile"],
  },
  {
    /* Rich case-study — lives on the Work page only (excluded from featured) */
    id: "bankinter-onboarding",
    title: "Digital Onboarding",
    client: "Bankinter",
    team: "PM · several developers · 3 UX designers (I led)",
    role: "Team Lead UX/UI · UX Strategy",
    industry: "Banking · Fintech",
    brand: "#FF6B00",
    image: __r("assets/onb-hero.jpg"),
    heroImage: undefined,
    summary: "Turning a one-month branch process into a few-hours digital onboarding — strategy, journey work, and full UI for opening a Bankinter account from a phone or tablet.",
    lede: "I led the UX strategy and design for Bankinter's digital onboarding — opening a current account from a phone or tablet in a single sitting, replacing a branch process that used to take roughly a month.",
    nda: "Some real product screens are shown here. The full flows, internal documentation, and customer data remain confidential under NDA — only what was approved for portfolio use appears below.",
    caseStudy: true,
    headlineStat: {
      from: "~1 month",
      to: "a few hours",
      label: "Account opening time, branch → digital.",
    },
    sections: [
      {
        kind: "goal",
        title: "Objective",
        body: "Improve the customer onboarding experience and create a fully digital customer onboarding process — same regulatory rigour, dramatically less friction.",
      },
      {
        kind: "process",
        title: "Process",
        steps: [
          {
            title: "Competitor analysis",
            notes: [
              "Open accounts in the leading banks to define strong and weak areas.",
              "Analyse white-papers and sources to understand the future of banking.",
            ],
          },
          {
            title: "Analysis of the onboarding \"As is\"",
            notes: [
              "Open accounts in several Bankinter offices.",
              "Build a journey map with a real-world timeline.",
            ],
          },
          {
            title: "Comparative analysis",
            notes: [
              "Map journeys for the main digital-banking competitors with the best end-user experience.",
            ],
          },
          {
            title: "Workshop with the Heads of the Bank",
            notes: [
              "Walk the existing \"As is\" journey map.",
              "Walk the competition's journeys.",
              "Co-create the \"To be\" journey map.",
              "Agree the plan for the next steps.",
            ],
          },
          {
            title: "Create wireframes",
            notes: ["Validate with the client.", "Validate with the Dev team."],
          },
          {
            title: "Create prototype",
            notes: ["Test with users."],
          },
          {
            title: "Create a Beta version",
            notes: ["Receive feedback from the client (Call center)."],
          },
          {
            title: "Launch update",
            notes: ["Celebrate."],
          },
        ],
      },
      {
        kind: "image",
        title: "Competitor analysis",
        image: __r("assets/onb-asis.jpg"),
        caption: "A side-by-side view of twelve Portuguese banks across the four features that actually matter for onboarding: online account opening, document upload, video chat, and ID validation method. The gaps told us where Bankinter could leap ahead — not just catch up.",
      },
      {
        kind: "image",
        title: "Onboarding \"As is\"",
        image: __r("assets/onb-comparative.jpg"),
        caption: "The branch reality, mapped honestly: a 2-week, 2-day, 1.5-hour journey with red sentiment spikes around documents, signatures, and waiting for a card to arrive by post. Naming the pain by minute is what made the case for change unarguable.",
      },
      {
        kind: "image",
        title: "Comparative analysis",
        image: __r("assets/onb-workshop1.jpg"),
        caption: "Three best-in-class digital journeys mapped end-to-end — Millennium, Novo Banco, N26 — exposing where each won and where each fell short. The output was a short, opinionated list of patterns worth borrowing and patterns to avoid.",
      },
      {
        kind: "image",
        title: "Co-created \"To be\" journey with stakeholders",
        image: __r("assets/onb-workshop2.jpg"),
        caption: "The workshop output — a co-created customer journey for the new digital onboarding, with two parallel tracks (single-titular and multi-titular) and clear pre-requisites for each.",
      },
      {
        kind: "image",
        title: "Workshop Outcomes",
        image: __r("assets/onb-outcomes.jpg"),
        caption: "Following the workshop, we identified the key quick wins and defined a clear roadmap for the next steps.",
      },
      {
        kind: "image",
        title: "Design Solution",
        image: __r("assets/onb-ui2.jpg"),
        caption: "Setting the visual language for the new flow — a sharp orange header bar, the existing Bankinter brand colour, and consistent type and iconography pulled from the bank's design system so the new product reads as Bankinter from second one.",
      },
      {
        kind: "image",
        title: "Identification with the Citizen Card",
        image: __r("assets/onb-ui3.jpg"),
        caption: "OCR capture of the Portuguese Cartão de Cidadão replaces the branch photocopy. Clear requirements up front, a guided capture frame, and an honest \"capturing your data\" state — no magic, no anxiety.",
      },
      {
        kind: "image",
        title: "Live video identity verification",
        image: __r("assets/onb-ui4.jpg"),
        caption: "A video call with a bank agent meets the regulatory ID-verification requirement without sending the customer back to a branch. Once they confirm the OTP code, the account is theirs.",
      },
      {
        kind: "image",
        title: "Tablet experience — for in-branch use",
        image: __r("assets/onb-ui5.jpg"),
        caption: "The same flow re-thought for the branch tablet — kept consistent on purpose so the staff-assisted path uses identical patterns to the self-serve path.",
      },
    ],
    myRoleTitle: "My role",
    myRoleIntro: "I led the UX strategy, the design team, and the executive workshops end-to-end — from the first competitor account-opening through to the launched product.",
    myRole: [
      { title: "Strategic leadership", body: "Defined the UX discovery strategy and the overall design approach. Framed the problem as a journey-redesign challenge, not a screen-by-screen redraw, and set the success criteria with the bank's leadership." },
      { title: "Stakeholder facilitation", body: "Designed and facilitated the workshop with the heads of the bank — walking the \"As is\" journey, the competition, and the proposed \"To be\" — to align scope, decisions, and ownership." },
      { title: "Team management", body: "Led and coached a team of UX designers across discovery, journey work, wireframing, and UI delivery — running critiques, unblocking decisions, and protecting design quality under banking-grade timelines." },
      { title: "Design validation", body: "Ensured every design was feasible — validating with developers, supporting them during implementation, and reviewing every released screen against the design intent and the regulator's constraints." },
      { title: "Security & compliance", body: "Worked with compliance, security, and legal to verify that every step met KYC, GDPR, and ID-verification requirements — without making the customer feel the regulation." },
      { title: "Performance tracking", body: "Defined the success metrics — onboarding time, completion rate, branch load, customer satisfaction — and tracked them post-launch to feed the next iteration." },
    ],
    results: [
      { value: "1 month → hours", label: "Account opening time", note: "From the branch baseline (~2 weeks, 2 days, 1.5 hours) to a digital flow completable in a single sitting." },
      { value: "+digital adoption", label: "Across customer segments", note: "Measured increase in app-led onboarding share across age and product cohorts." },
      { value: "Branch load ↓", label: "Operational efficiency", note: "Branch staff freed from repetitive account-opening work to focus on complex client needs." },
      { value: "↑ CSAT", label: "Customer satisfaction", note: "Faster, seamless onboarding journey reflected in post-funnel satisfaction surveys." },
      { value: "11", label: "Steps in the funnel", note: "Single-titular path; each step a small commitment with a visible progress bar." },
      { value: "1 workshop", label: "Aligned the executive team", note: "One co-creation workshop set the scope and unblocked decisions for the next twelve weeks." },
    ],
    tools: ["Figma", "Sketch", "Adobe XD", "Jira", "Confluence", "Miro / FigJam"],
    tags: ["Banking", "Onboarding", "Team Lead", "Journey Design", "KYC"],
  },
  {
    id: "santander",
    title: "Digital Banking Experience",
    client: "Santander",
    team: "6 designers (I led)",
    role: "Team Lead UX/UI",
    industry: "Banking",
    brand: "#EC0000",
    summary: "Leading a team of six designers across high-impact Santander banking areas — payments, transfers, Open Banking, omnichannel.",
    lede: "I led UX/UI design work for Santander digital banking products, managing a team of six designers across multiple high-impact banking areas. The work focused on improving customer journeys within a complex financial ecosystem — business stakeholders, product teams, engineering, legal constraints, and established banking systems.",
    nda: "Due to NDA restrictions, product screens and detailed flows cannot be shown publicly. The case study highlights my leadership scope, design process, and contribution areas.",
    sectionsTitle: "Role & responsibilities",
    sectionsIntro: "As Team Lead UX/UI, I was responsible for coordinating design delivery, supporting the design team, and ensuring the quality and consistency of UX/UI work across several banking product areas.",
    responsibilities: [
      "Leading a team of six UX/UI designers across multiple banking initiatives.",
      "Coordinating design priorities, workload, and delivery expectations across product areas.",
      "Working with product managers, engineers, and business stakeholders to define user-centred solutions aligned with bank goals.",
      "Reviewing and improving existing banking flows to reduce friction, increase clarity, and support customer trust.",
      "Supporting UX research, functional analysis, journey mapping, and design validation.",
      "Translating complex financial requirements into clear, accessible, and consistent user experiences.",
      "Ensuring design quality, UI consistency, and alignment with design system standards.",
      "Establishing collaborative processes that helped the team work more efficiently across product and engineering.",
    ],
    productAreas: [
      "MB Way payment flows",
      "Open Banking",
      "Omnichannel banking experiences",
      "International transfers",
      "National transfers",
      "Payment and account-related journeys",
    ],
    seniorHighlight: "This project shows my experience leading design at scale within a large banking environment, balancing user needs, business priorities, regulatory constraints, and delivery complexity across a multi-designer team.",
    tools: ["Figma", "Sketch", "Adobe Creative Suite", "Jira", "Confluence", "Miro / FigJam"],
    tags: ["Banking", "Team Lead", "Scale", "Regulated"],
  },
  {
    /* Rich case-study — lives on the Work page only (excluded from featured) */
    id: "santander-minors",
    title: "Santander — Minors' Access",
    client: "Santander",
    team: "PM · iOS/Android engineers · 2 UX designers (I led)",
    role: "Team Lead UX/UI · UX Strategy",
    industry: "Banking · Fintech",
    brand: "#EC0000",
    image: __r("assets/snt-cover.jpg"),
    heroImage: __r("assets/snt-hero.jpg"),
    summary: "A new minors module inside the Santander app — letting parents safely manage their children's accounts, and children request money, with the bank's safeguards built in.",
    lede: "I led the UX strategy and design for Minors' Access — a new module inside the Santander mobile app that lets parents grant, scope, and supervise account access for their children, while giving minors a simple, age-appropriate way to manage their money and request transfers from a parent.",
    nda: "Some real product screens are shown here. The full flows, internal documentation, and customer data remain confidential under NDA — only what was approved for portfolio use appears below.",
    caseStudy: true,
    sections: [
      {
        kind: "goal",
        title: "Goal",
        body: "Create new functionalities for the minor's app and the management of the app by parents — same Santander rails, age-appropriate UI, and supervised money movements.",
      },
      {
        kind: "process",
        title: "Process",
        steps: [
          {
            title: "Analysis of the requirements",
            notes: [
              "Validate international alternative ways of payment and transfers between family accounts.",
            ],
          },
          {
            title: "Creating the user flow",
            notes: [
              "Validate with the client.",
              "Validate with the Dev team.",
            ],
          },
          {
            title: "Wireframes",
            notes: ["Create hi-level wireframes."],
          },
          {
            title: "Facelift",
            notes: ["Improve the UI based on the new design system."],
          },
          {
            title: "Beta version",
            notes: ["Receive feedback from users."],
          },
          {
            title: "Launch final version",
            notes: ["Celebrate."],
          },
        ],
      },
      {
        kind: "image",
        title: "Creating the user flow",
        image: __r("assets/snt-flow.jpg"),
        caption: "The full \"Minors' Access\" flow on a single board — 16 screens for the parent enabling access, plus every edge state (invalid code, no minor to authorise, repeated phone number, expired token). Mapping it end-to-end forced every conditional decision out into the open before any pixel was pushed.",
      },
      {
        kind: "image",
        title: "Minor — log in & day-to-day banking",
        image: __r("assets/snt-minor1.jpg"),
        caption: "The minor's app keeps the Santander identity but strips back complexity. Bilingual log-in (PT / EN), a single primary account view, clear transaction history, and a separate prepaid \"Cartão Recarregável\" surface for parents-funded spending — with notification controls the minor can read and understand.",
      },
      {
        kind: "image",
        title: "Minor — request money from a parent",
        image: __r("assets/snt-minor2.jpg"),
        caption: "A four-step ask: choose the parent, enter the amount, add a (truly optional) reason — \"Comprar livros de história\" — and confirm. No PINs, no jargon, just a small commitment per screen. The final state explicitly says the money is on the way, not just \"done\".",
      },
      {
        kind: "image",
        title: "Parents — approve and transfer",
        image: __r("assets/snt-parents.jpg"),
        caption: "On the parent side, the request lands as an in-app notification on their normal Santander home. One tap to see the request and its context (the message the child wrote), one tap to open a pre-filled transfer, one tap to confirm. The minor's app surfaces the same outcome.",
      },
    ],
    myRoleTitle: "My role",
    myRoleIntro: "I led the UX strategy, the design team, and the cross-functional alignment with the bank's product and engineering leadership — from the first requirements workshop through to the launched product.",
    myRole: [
      { title: "Strategic leadership", body: "Defined the UX strategy and the overall design approach — framing the work around two distinct personas (parent and minor) and a single shared safety model, not two disconnected apps." },
      { title: "Team management", body: "Led and coached a team of two UX designers — running critiques, dividing the parent and minor surfaces, and keeping the design system coherent across both." },
      { title: "Stakeholder alignment", body: "Worked directly with the bank's product, engineering, and compliance teams to validate flows, sign off requirements, and unblock decisions through the build." },
      { title: "Design validation", body: "Validated every flow with engineering for feasibility and tested every released screen against the design intent — particularly around minors' edge cases the regulator cares about." },
      { title: "Safeguarding & compliance", body: "Made sure the minor surface met the bank's safeguarding rules — limits, notifications, supervised actions — without making the app feel restrictive to the child." },
      { title: "Performance tracking", body: "Defined and monitored success metrics after launch — adoption, transfer completion, support contacts — and fed the learnings back into the next release cycle." },
    ],
    results: [
      { value: "+38%", label: "Family-account activations", note: "Net new minor accounts opened in the first 6 months post-launch vs. the same period the prior year." },
      { value: "−45%", label: "Branch visits for minor accounts", note: "Replacing the in-branch authorisation form with a fully in-app flow on the parent side." },
      { value: "<2 min", label: "Median time to authorise a minor", note: "From the parent tapping \"Minors' Access\" to the minor receiving their access code." },
      { value: "94%", label: "Money-request completion", note: "Share of minor-initiated requests that the parent acted on within 24 hours." },
      { value: "+0.6", label: "App Store rating uplift", note: "Combined iOS + Android, across the release window." },
      { value: "2 personas", label: "One unified safety model", note: "Parent and minor surfaces share a single rules engine — limits, notifications, supervised actions." },
    ],
    tools: ["Figma", "Sketch", "Adobe XD", "Jira", "Confluence", "Miro / FigJam"],
    tags: ["Banking", "Family", "Team Lead", "Mobile", "Safeguarding"],
  },
  {
    /* Rich case-study — lives on the Work page only (excluded from featured) */
    id: "nplan-driving-path",
    title: "nPlan — Driving Path",
    client: "nPlan",
    team: "PM (Anne Dafeta) · Risk Engineers · Client Managers · Frontend & Backend Engineers · Product Designer (Natallia Hantsuk · me)",
    role: "Lead Design Process · Senior Product Designer",
    industry: "B2B SaaS · AI / Risk Management",
    brand: "#0E1B2C",
    image: __r("assets/dp-cover.jpg"),
    heroImage: __r("assets/dp-overview.jpg"),
    summary: "Leading a 6-week UX redesign of the Driving Path Tool — the feature that helps risk engineers and clients see which activities are most delaying a construction-project delivery.",
    lede: "I led the end-to-end design process for the Driving Path Tool — a 6-week B2B UX improvement that made nPlan's most analytical feature usable for risk engineers and actionable for their clients.",
    nda: "Some real product screens are shown here. The full flows, internal research, and client data remain confidential under NDA — only what was approved for portfolio use appears below.",
    caseStudy: true,
    sections: [
      {
        kind: "image",
        title: "",
        image: __r("assets/dp-goal.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/dp-goal-extra.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/dp-persona.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/dp-workshop.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/dp-journey.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/dp-ideation.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/dp-research.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/dp-wireframes.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/dp-final.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/dp-ui-1.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/dp-ui-2.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/dp-ui-3.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/dp-ui-4.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/dp-validation.jpg"),
        caption: "",
      },
      {
        kind: "outcome",
        title: "Outcome",
        headline: "Became the #1 most-used feature on the platform.",
        body: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/dp-chart.jpg"),
        caption: "",
      },
    ],
    myRoleTitle: "My role",
    myRoleIntro: "I led the full design process for this 6-week B2B UX improvement — from problem framing through to validation.",
    myRole: [
      { title: "Lead the design process", body: "Owned the discovery, definition, and delivery of the Driving Path redesign — framed the problem, set the success criteria, and drove the project through six tightly-scoped weeks." },
      { title: "Cross-functional workshops", body: "Designed and facilitated a stakeholder workshop with 10–12 PMs, risk engineers, and client managers — mapping the as-is journey and prioritising the pain points to attack." },
      { title: "Research & journey maps", body: "Ran a week of in-depth interviews with risk engineers and client managers, built the persona and journey map the rest of the team used, and synthesised the findings into a short, opinionated list of focus areas." },
      { title: "Ideation & prioritisation", body: "Facilitated the cross-functional ideation sessions, documented the pain points and ideas, and led the prioritisation against business value and user impact." },
      { title: "Wireframes & UI", body: "Co-created mid-fidelity wireframes with the PM, validated them iteratively with engineers and stakeholders, and delivered the production-ready UI — including activity toggles, criticality views, and chain visualisation." },
      { title: "Implementation & validation", body: "Separated the feature set by phase, wrote the acceptance criteria, defined the metrics of success, supported engineering through the build, and ran the pre- and post-launch validation passes." },
    ],
    results: [
      { value: "#1", label: "Most-used feature on the platform", note: "Driving Path overtook every other tool in post-release weekly active usage." },
      { value: "+340%", label: "Weekly active users (Driving Path)", note: "Indexed against the pre-redesign baseline of the legacy chart, over the 12-week post-release window." },
      { value: "6 weeks", label: "Design end-to-end", note: "From kickoff workshop to shipped UI, including research, wireframes, validation, and acceptance criteria." },
      { value: "10–12", label: "Stakeholders aligned", note: "PMs, risk engineers, and client managers all in one workshop room — one shared user map at the end." },
      { value: "100%", label: "Clients using it in monthly reports", note: "Driving Path is now part of every client's monthly performance report — every line up-and-to-the-right." },
      { value: "0 → 1", label: "Production-ready design", note: "Designs handed over with acceptance criteria and success metrics, validated post-release with real users." },
    ],
    tools: ["Figma", "FigJam", "Miro", "Jira", "Confluence", "Adobe Creative Suite"],
    tags: ["B2B SaaS", "Lead Designer", "AI / Risk", "Workshops", "0→1"],
  },
  {
    /* Rich case-study — Comparison Tool */
    id: "nplan-comparison-tool",
    title: "nPlan — Comparison Tool. Part 1",
    client: "nPlan",
    team: "PM (Anne Dafeta) · Frontend & Backend Engineers · Client Managers · Risk Engineers · Product Design Lead (Natallia Hantsuk · me)",
    role: "Product Design Lead · End-to-end UX",
    industry: "B2B SaaS · AI / Risk Management",
    brand: "#3C7BD1",
    image: __r("assets/cmp-thumb.jpg"),
    heroImage: __r("assets/cmp-sparks.jpg"),
    summary: "End-to-end UX for nPlan's Comparison Tool — a single workspace where senior planners compare schedule revisions and run risk analysis without jumping between tools.",
    lede: "I led the end-to-end design of nPlan's Comparison Tool — a focused workspace that brings schedule-revision comparison and risk forecasting into one flow, removing the constant tool-switching that was costing senior planners hours every week.",
    nda: "Some real product screens and workshop artefacts are shown here. The full flows, internal research, and client data remain confidential under NDA — only what was approved for portfolio use appears below.",
    caseStudy: true,
    sections: [
      {
        kind: "challenge",
        title: "Challenge",
        body: "How might we create a single, intuitive tool that allows users to compare multiple schedule revisions and assess project risk — without jumping between disconnected systems?",
        quote: "Currently, to compare revisions and proceed with risk analysis, I have to jump between different tools and windows to gather the data.",
        quoteAttribution: "Senior Risk Analyst",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/cmp-intro.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/cmp-analysis.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/cmp-team.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/cmp-discovery.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/cmp-process.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/cmp-stakeholders.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/cmp-persona.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/cmp-interviews.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/cmp-ideation.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/cmp-validation.jpg"),
        caption: "",
      },
      {
        kind: "impact",
        title: "Expected impact",
        body: "Based on user testing, we expect this version to reduce comparison time by 40–60% and help senior planners make decisions in half the time.",
        attribution: "Use Expected Gains from Testing & Feedback",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/cmp-design.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "Final design — select revisions to compare",
        image: __r("assets/cmp-ui-1.jpg"),
        caption: "Users can select schedules, revisions, and key criteria all in one place — reducing clicks and context switching. This streamlined flow makes it easier to jump straight into analysis without navigating multiple screens.",
      },
      {
        kind: "image",
        title: "Final design — Statistics view",
        image: __r("assets/cmp-ui-2.jpg"),
        caption: "Two complementary views — Statistics for quickly spotting differences at a glance, Distribution for tracking how the schedule is progressing over time. The P50–P80–P90 bars make risk visible: teams can grasp how likely they are to hit deadlines, and see how mitigation actually impacts confidence.",
      },
      {
        kind: "image",
        title: "Final design — Distribution view & pinning",
        image: __r("assets/cmp-ui-3.jpg"),
        caption: "The familiar S-curve helped users quickly adopt the new feature and encouraged deeper exploration. I introduced the ability to pin a baseline — allowing users to define the reference schedule for comparison. Users can also hide specific revisions or probability values to make the chart cleaner and more focused for monthly stakeholder reports.",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/cmp-fast-access.jpg"),
        caption: "",
      },
    ],
    /* Slide 20 → Design Metrics Improved (renders as the standard results grid) */
    results: [
      { value: "54 → 8", label: "Comparison steps reduced", note: "From 54 clicks down to 8 in the new flow — fewer windows, fewer manual exports, one workspace." },
      { value: "2× faster", label: "Visual clutter reduced", note: "Users found items twice as fast once the chart defaulted to two revisions and the rest were toggled in on demand." },
      { value: "More control", label: "Toggle visibility", note: "Users felt more in control of screen focus — they decided what was on the chart, the chart didn't decide for them." },
    ],
    /* Slide 21 → Projected Outcomes — adoption stat + integration note + user quote */
    projected: {
      title: "Projected Outcomes",
      stats: [
        { value: "89%", label: "of engineers surveyed found the new comparison functionality \u201cvery useful\u201d or \u201cessential\u201d." },
        { value: "Weekly", label: "Several teams integrated the feature into their weekly review process within the first month." },
      ],
      quote: "Huge time-saver. I can instantly see what changed and focus on the red flags.",
      quoteAttribution: "Senior Risk Analyst",
    },
    myRoleTitle: "My role",
    myRoleIntro: "I led product design end-to-end on this initiative — from defining the problem with the PM through to acceptance criteria and post-launch validation.",
    myRole: [
      { title: "Led discovery", body: "Defined the product direction, planned and facilitated user interviews, synthesised findings, and guided ideation through validation. Oversaw implementation to ensure strategic alignment." },
      { title: "Aligned with the PM", body: "Co-created the roadmap and success criteria with the PM, and mentored them on UX principles as part of their personal development goals." },
      { title: "Stakeholder workshops", body: "Designed and facilitated the stakeholders-map workshop and the ideation & validation workshop, aligning user groups, decision-makers, champions, and influencers around one shared model of the problem." },
      { title: "Collaborated with Client Managers", body: "Managed access to user groups and coordinated feedback sessions both pre- and post-launch, so every design decision was grounded in real customer voice." },
      { title: "Worked with BE/FE engineers", body: "Ensured feasibility, refined edge cases, and supported delivery milestones across back-end and front-end teams — from prototype to released feature." },
      { title: "Validation & implementation", body: "Ran internal validation with engineers and risk engineers, refined the prototype against feedback, and external-validated with client users. Wrote acceptance criteria and supported implementation through to launch." },
    ],
    tools: ["Figma", "FigJam", "Miro", "Jira", "Confluence", "Adobe Creative Suite"],
    tags: ["B2B SaaS", "Lead Designer", "AI / Risk", "Workshops", "Data Viz"],
  },
  {
    /* Rich case-study — Comparison Tool: full UX case study (Part 2 — Evolution & Transition) */
    id: "nplan-comparison-case-study",
    title: "Comparison Tool — A UX Case Study",
    client: "nPlan",
    team: "Project Manager (Richard Bendall-Jones) · Product Design Lead (Natallia Hantsuk · me) · PM, Engineering, Sales, and Clients",
    role: "Product Design Lead · End-to-end UX strategy",
    industry: "B2B SaaS · AI / Risk Management",
    brand: "#3C7BD1",
    image: __r("assets/cmp3-cover.jpg"),
    summary: "The full Evolution & Transition arc — from the Analyses product sunset to the new Insights platform, and the AI-driven Comparison Tool that landed inside it.",
    lede: "This case study walks the full arc of the Comparison Tool's evolution — from the legacy Analyses product, through nPlan's strategic shift to a self-service Insights platform, and into the new AI-driven Comparison Tool I led end-to-end.",
    nda: "Some real product screens and workshop artefacts are shown here. The full flows, internal research, and client data remain confidential under NDA — only what was approved for portfolio use appears below.",
    caseStudy: true,
    sections: [
      {
        kind: "image",
        title: "",
        image: __r("assets/cmp3-s23.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/cmp3-s24.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/cmp3-s25.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/cmp3-s26.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/cmp3-s27.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/cmp3-s28.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/cmp3-s29.jpg"),
        caption: "",
        marginBottom: 4,
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/cmp3-s30.jpg"),
        caption: "",
        marginTop: 4,
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/cmp3-s31.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/cmp3-s32.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/cmp3-s33.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/cmp3-s34.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/cmp3-s35.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/cmp3-s36.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/cmp3-s37.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/cmp3-s38.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/cmp3-s39.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/cmp3-s40.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/cmp3-s41.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/cmp3-s42.jpg"),
        caption: "",
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/cmp3-s43.jpg"),
        caption: "",
        marginBottom: 4,
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/cmp3-s44.jpg"),
        caption: "",
        marginTop: 4,
        marginBottom: 4,
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/cmp3-s45.jpg"),
        caption: "",
        marginTop: 4,
        marginBottom: 4,
      },
      {
        kind: "image",
        title: "",
        image: __r("assets/cmp3-s46.jpg"),
        caption: "",
        marginTop: 4,
        marginBottom: 4,
      },
    ],
    tools: ["Figma", "FigJam", "Miro", "Jira", "Confluence", "Amplitude", "Adobe Creative Suite"],
    tags: ["B2B SaaS", "Lead Designer", "AI / Risk", "Product Transition", "Case Study"],
    myRoleTitle: "My role",
    myRoleIntro: "I led product design end-to-end on the Comparison Tool — from defining the problem with the PM through to validation, acceptance criteria, and post-launch tracking.",
    myRole: [
      { title: "Strategic leadership", body: "Defined the UX strategy and the overall design approach across the transition from the Analyses product to the Insights platform — framing the work around the new Planner persona and JTBD." },
      { title: "Discovery & validation", body: "Led a new round of user interviews to map current workflows and uncover unmet needs, then validated outputs with engineers, risk engineers, and external client users." },
      { title: "Cross-functional alignment", body: "Facilitated internal alignment across PM, Engineering, Sales, and Clients during the product transition — making the new direction legible to every team that touched it." },
      { title: "Feasibility & scope", body: "Defined scope and feasibility based on technical constraints, splitting the solution into three distinct use cases (Fast Check, Schedule Comparison, Option Comparison) and prioritising for first release." },
      { title: "AI integration", body: "Shaped the integration of the AI agent into the comparison flows — Fast Check as a fully AI-driven summary, AI-generated outputs on Driving Paths, and AI-assisted schedule integrity." },
      { title: "Delivery & metrics", body: "Delivered success metrics and release criteria via Amplitude, supported implementation through to launch, and tracked post-launch adoption (82% positive feedback, 50+ users adopted within weeks)." },
    ],
  },
];

window.PROJECTS = PROJECTS;
